theme: null
layouts_dir: "./_template/layouts"
includes_dir: "./_template/layouts"
kramdown:
  input: "GFM"
exclude: [ "vendor", ".jekyll-cache" ]
include: [ "_template" ]
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "index.md"
      type: "pages"
    values:
      layout: "home"
  -
    scope:
      path: "posts/index.md"
      type: "pages"
    values:
      layout: "posts-list"
  -
    scope:
      path: "programs/index.md"
      type: "pages"
    values:
      layout: "programs-list"
  -
    scope:
      path: "testimonials/index.md"
      type: "pages"
    values:
      layout: "testimonials-list"
  -
    scope:
      path: "posts/*.md"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "programs/*.md"
      type: "pages"
    values:
      layout: "program"
  -
    scope:
      path: "testimonials/*.md"
      type: "pages"
    values:
      layout: "testimonial"
  -
    scope:
      path: "header.md"
      type: "pages"
    values:
      layout: "header"
  -
    scope:
      path: "footer.md"
      type: "pages"
    values:
      layout: "footer"
plugins:
 - jekyll-optional-front-matter
 - jekyll-titles-from-headings
optional_front_matter:
  remove_originals: true
livereload: true
